### ISSUE TITLE
Release v4.9.0.1 missing

### ISSUE THREAD

**Issue by b-bittner** [pcengines/pcengines.github.io#22] opened 2019-02-01 08:26 UTC
Hi,
I'm not quite sure if this is the right place/way to ask for this.
Is there a reason why the newest Coreboot-Release (v4.9.0.1) is missing in the official [documentation](https://pcengines.github.io/) ?

**Comment by pietrushnic** [comment] 2019-02-03 22:46
@b-bittner it is fine. I get the same question over PC Engines forum. This was my fault and mess caused by not adding binaries to the first newsletter. We will improve that soon - Monday EOD website should be fixed.

**Comment by miczyg1** [comment] 2019-02-05 09:23
@b-bittner v4.9.0.1 release has been added. I am closing the issue.

**Closed by miczyg1** 2019-02-05 09:23 UTC

**Comment by b-bittner** [comment] 2019-02-05 11:02
@**all**, thanks for uploading and updating the page. Would it be possible to add md5-sum files to the tar-archive, like in the releases before?

**Comment by miczyg1** [comment] 2019-02-05 11:05
@b-bittner we began to sign the images. We will upgrade the site soon with SHA256 signatures and digests, so that everyone could verify the binaries.

**Comment by b-bittner** [comment] 2019-02-05 12:30
@miczyg1 ah, that's nice. Looking forward for it.
